# Generated by Django 5.2.7 on 2025-11-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_category_alter_post_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorys',
        ),
    ]
